[package]
name = "hourglass"
version = "0.1.0"
edition = "2021"

[dependencies]
# In-house deps
hourglass-model = { path = "../model" }

# Standard deps
axum = "0.6.20"
shuttle-axum = "0.31.0"
shuttle-runtime = "0.31.0"
tokio = "1.33.0"
